# Generated by Django 5.0.7 on 2024-07-24 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Идентификатор для слага; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Жанр книги',
                'verbose_name_plural': ('Жанры книг',),
            },
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Идентификатор для слага; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Жанр игры',
                'verbose_name_plural': 'Жанры игр',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Идентификатор для слага; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': ('Жанры',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('original_title', models.CharField(max_length=250, verbose_name='Оригинальное название')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выхода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('genre', models.ManyToManyField(related_name='movies', to='content.moviegenre')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.status')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('title', 'year', 'user'), name='unique_movie'),
        ),
    ]
