# Generated by Django 5.0.7 on 2024-07-25 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviegenre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=100, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('original_title', models.CharField(max_length=100, verbose_name='Оригинальное название')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выхода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('genre', models.ManyToManyField(related_name='serials', to='content.moviegenre')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AddConstraint(
            model_name='serial',
            constraint=models.UniqueConstraint(fields=('title', 'year', 'user'), name='unique_serial'),
        ),
    ]
