# Generated by Django 5.0.7 on 2024-07-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_book_book_unique_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookgenre',
            options={'verbose_name': 'Жанр книги', 'verbose_name_plural': 'Жанры книг'},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
