# Generated by Django 5.0.7 on 2024-08-22 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_bookgenre_options_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-year', 'pub_date'), 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-year', 'pub_date'), 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-year', 'pub_date'), 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ('-year', 'pub_date'), 'verbose_name': 'Сериал', 'verbose_name_plural': 'Сериалы'},
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1445, message='Минимальный год 1445'), django.core.validators.MaxValueValidator(2100, message='Максимальный год 2100')], verbose_name='Год выхода'),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1445, message='Минимальный год 1445'), django.core.validators.MaxValueValidator(2100, message='Максимальный год 2100')], verbose_name='Год выхода'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1445, message='Минимальный год 1445'), django.core.validators.MaxValueValidator(2100, message='Максимальный год 2100')], verbose_name='Год выхода'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1445, message='Минимальный год 1445'), django.core.validators.MaxValueValidator(2100, message='Максимальный год 2100')], verbose_name='Год выхода'),
        ),
    ]
